### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by zlx913** [Haru-zt/DDPLS#4]
According to the log output, the memory keeps changing and generally shows an increasing trend. Is this normal?

**Comment by Haru-zt** [comment]
Sorry, I don't notice this problem, it will cause a memory leak issue?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haru-zt/DDPLS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月27日(星期天) 晚上8:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Haru-zt/DDPLS] memory problem (Issue #4)





 
According to the log output, the memory keeps changing and generally shows an increasing trend. Is this normal?
