### ISSUE TITLE
KeyError: 'PseudoAngleCoder is not in the mmrotate::task util regist 

### ISSUE THREAD

**Issue by YangZeW** [Haru-zt/DDPLS#5]

**Comment by Haru-zt** [comment]
Maybe you should use the code in edition mode.
like pip install -e .



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 12, 2024 15:14 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Haru-zt/DDPLS] KeyError: 'PseudoAngleCoder is not in themmrotate::task util regist  (Issue #5)

**Comment by clanguagesh** [comment]
do you solve this problem, i encoutered the same issue

**Comment by Haru-zt** [comment]
Can you try the new code and test this issue again? I just upload a new version. Thanks you.

**Comment by Haru-zt** [comment]
That is quite strange as i Never meet this problem. But I know register in mmrotate is quite hard to use. So that could happen.  Let me know when it will happen.

**Comment by clanguagesh** [comment]
> 这很奇怪，因为我从来没有遇到过这个问题。但是我知道在 mmrotate 中注册很难使用。所以这可能会发生。请告诉我什么时候会发生。

File "/home/sh/semi-obb/DDPLS-main/DDPLS-main/mmrotate/models/dense_heads/rotated_fcos_head.py", line 84, in __init__
    self.angle_coder = TASK_UTILS.build(angle_coder)
  File "/home/sh/anaconda3/envs/ddpls/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/sh/anaconda3/envs/ddpls/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'PseudoAngleCoder is not in the mmrotate::task util registry. Please check whether the value of `PseudoAngleCoder` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

this is my error information

**Comment by Haru-zt** [comment]
ok, i will make a new env to test

**Comment by clanguagesh** [comment]
I find your code lose some py file in task_modules, i copy these files from mmrotate 1.x, and then the code can run now

**Comment by clanguagesh** [comment]
sorry, i didn't find your latest code, i'll try again. I find your new code has added those files i copied from mmrotate 1.x

**Comment by Haru-zt** [comment]
yes, in fact it was a rep at the beginning. but when I find i can't upload the whole rep because of the wrong network, i have to upload it  separate. That is bad choice~~~. It glad to see you solve the problem . Have good day!

**Comment by Haru-zt** [comment]
> ok, i will make a new env to test

I make a env and find it well! I am sure I have solved this problem. If you have any other problem, let me know!
